### ISSUE TITLE
Add support for Alpine

### ISSUE THREAD

**Issue by DrStrangepork** [timo-reymann/circleci-orb-deterministic-zip#9]
We often build on [python](https://hub.docker.com/_/python/), but [bboe/deterministic_zip](https://github.com/bboe/deterministic_zip) does not result in the same hash as our local build environments of Windows and macOS where we use [deterministic-zip](https://github.com/timo-reymann/deterministic-zip). We'd like to use the latter on our Python images instead of deterministic_zip, so we can have a consistent archive across all platforms. Thanks!

**Comment by timo-reymann** [comment]
Hi @DrStrangepork,
foremost, thanks for opening an issue for the support. Currently, Alpine is not officially supported by deterministic-zip, and therefore I don't provide prebuilt binaries for it.

While I definitely see the use case for this, it will require some more testing and changes to the current pipeline as well. That's because Alpine uses musl, and the kernel is compiled using that tool chain instead of the GNU C Compiler (gcc). So technically, it's an entirely different clib.

Go is normally abstracting the details away, but I want to a 100% sure everything works as expected.

Currently, don't have the capacity to do it. So, I cannot provide you with a clear timeline or if it will ever be officially supported at all.

What you can try is to use the “[go install way](https://github.com/timo-reymann/deterministic-zip#install-with-go)”. This way, you would need go installed in addition to the python toolchain. Combined with docker multi-stage images, you can also prebuild it using an alpine-based go container.

If you are using the CircleCI Cloud, I would strongly recommend going for [`cimg/python`](https://circleci.com/developer/images/image/cimg/python) anyway. The base layers are always cached and its optimized for use with the ecosystem.

Cheers
Timo

**Comment by DrStrangepork** [comment]
FWIW, this is what I ended up building for my use: https://github.com/DrStrangepork/deterministic-zip

**Comment by timo-reymann** [comment]
@DrStrangepork Sorry for the late response, if you encounter no problems with using it on Alpine I can also integrate it into the main project.

Not sure if I will go the same way as you and disable cgo or provide a musl version of it.

Also If its okay for you I would add it to the README that there is the project for interested people

**Comment by timo-reymann** [comment]
With version 2+ all binaries can run without libc dependencies (gblic, musl)
